DELETE http://localhost:3001/api/persons/3

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Greatest Ever",
    "number": "1-800-HOTLINE"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "1-800-HOTLINE"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Cool Name",
    "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "05-06060606"
}
###
GET http://localhost:3001/api/persons/malFormattedId

###
PUT http://localhost:3001/api/persons/60e3aa21b85be959f90864ec